language: java

# Cache Dependencies
cache:
  directories:
    - "$HOME/.m2"
    - '$HOME/.sonar/cache'

env:
  global:
    - CODECOV_TOKEN="5357ed51-b2ca-4eec-a16d-fe3c9dba438c"

addons:
  sonarcloud:
    organization: "tobi6112"
    token:
      secure: "euqvu/tHzIGP71SlNijpcynRKInVKdqKTle45tUm5zxna5IzS9npQ5yHTkxJvhD66ToiRsbWLES1Y4Hy5iECvMOvqFP8hii3NF78X1HSXsdsMTNFq1UIupOUHyphWATZTruD+LrBcyzyDon4u7JVdm6GqaKi2xT2kjEjpi5oaD0b753rv4OM+i5ioL1pxodKRxNUgZe3UhVZuVSCzbOq06SMVeYD8vKssHwoKj8EOVunBx2Hv6AdkHPk/hl1VT576jwzJXcKqAGo1Eb+SFzrL6HJMjk7C9q+amF2Aa/VhlGtyAns/FvbpBOwLQEfEwlXUbW9sUkS/6VQ7j8QXTJuk6OTQmeXTgwhmSN45nYVs7sqtWOre1XKlvjf6lXZF/Yb3PFwbyVZEHbElewmee4mJx5XePmlU3JNjC4U/bzTwx5sgRVMEP92aX0seDpD/UoxrA7qsHezRHpJU2Pj4eaxTeRW69JnwFzTMk5XBhrTlxXHezDLeJ/dh8ICidTFKb+oUj18Tl0PSvla/fICUI3IdbJSL1Gmwe4CtcyWYcnHlgeeSpQN4E+aE/kJG76QnUQzSYPsXYtQ1fGJx79PZnEvpt05nMppjd5idBHYLDNF/vhFwr8XaCh+tznCJ0QAW/1aq7gFFNTm5TbViAbFum3xGWFlz4mM9N4+aAeawd+Pwps="

jobs:
  include:
    - stage: build
      script: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V
      jdk: openjdk11
      name: Build (OpenJDK 11)
    - stage: build
      script: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V
      jdk: oraclejdk11
      name: Build (Oracle JDK 11)
    - stage: codequality
      script: mvn spotless:check
      jdk: openjdk11 #Run Only with OpenJDK 11 as it's a code style verification
      name: Spotless Code Check
    - stage: test
      script: mvn test -B
      jdk: openjdk11
      name: Unit Test (OpenJDK 11)
    - stage: test
      script: mvn test -B
      jdk: oraclejdk11
      name: Unit Test (Oracle JDK 11)
    - stage: codequality
      script: mvn install sonar:sonar -Dsonar.projectKey=tobi6112_demoproject
      name: SonarCloud

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Only on master branch
branches:
  only:
    - master
    - dev-tobi