language: java

# Cache Dependencies
cache:
  directories:
    - "$HOME/.m2"

env:
  global:
    - CODECOV_TOKEN=dc14bc46-660d-489e-b008-aeb09b14b888

install:
  - mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V

# Build with OpenJDK and Oracle JDK
jdk:
  - openjdk11
  - oraclejdk11

jobs:
  include:
    - stage: test
      script: mvn spotless:check
      jdk: openjdk11 #Run Only with OpenJDK 11 as it's a code style verification
      name: Spotless Code Check
    - stage: test
      script: mvn test -B
      name: Unit Test

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Only on master branch
branches:
  only:
    - master